M48
; DRILL file {KiCad 7.0.9+dfsg-1} date Rab 29 Nov 2023 04:19:39 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-29T16:19:39+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X4.585Y-2.4854
T2
X4.585Y-4.9866
X5.215Y-2.8134
T0
M30
